// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)
import WeeklyGoalsController from "./weekly_goals_controller"
import HealthWinFormController from "./health_win_form_controller"
import WeightChartController from "./weight_chart_controller"
import CalorieStatusController from "./calorie_status_controller"

application.register("weekly-goals", WeeklyGoalsController)
application.register("health-win-form", HealthWinFormController)
application.register("weight-chart", WeightChartController)
application.register("calorie-status", CalorieStatusController)

import ExerciseEntryFormController from "./exercise_entry_form_controller"
application.register("exercise-entry-form", ExerciseEntryFormController)

import BookCoverController from "./book_cover_controller"
application.register("book-cover", BookCoverController)

import LiteraryEditorController from "./literary_editor_controller"
application.register("literary-editor", LiteraryEditorController)

import NarrativePanelController from "./narrative_panel_controller"
application.register("narrative-panel", NarrativePanelController)
