// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import ExerciseCategoryController from "./exercise_category_controller"
application.register("exercise-category", ExerciseCategoryController)
import WeeklyGoalsController from "./weekly_goals_controller"
import HealthWinFormController from "./health_win_form_controller"
import WeightChartController from "./weight_chart_controller"
import CalorieStatusController from "./calorie_status_controller"

application.register("weekly-goals", WeeklyGoalsController)
application.register("health-win-form", HealthWinFormController)
application.register("weight-chart", WeightChartController)
application.register("calorie-status", CalorieStatusController)
