
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: <%= ENV.fetch("FINANCIAL_MANAGER_DATABASE_PATH", "/mnt/g/Meu Drive/OUTROS/gerenciador_financeiro/financial_manager.sqlite3") %>


test:
  <<: *default
  database: tmp/test.sqlite3


production:
  <<: *default
  database: <%= ENV.fetch("FINANCIAL_MANAGER_DATABASE_PATH", "/mnt/g/Meu Drive/OUTROS/gerenciador_financeiro/financial_manager.sqlite3") %>
