
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres.oiedvaxitboedsdkulhd
  password: VCFsCbJbdHv03Fus
  host: aws-1-sa-east-1.pooler.supabase.com
  port: 6543
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool_mode: transaction


development:
  <<: *default
  database: postgres


test:
  <<: *default
  database: postgres


production:
  <<: *default
  database: postgres