default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL_FINANCIAL_MANAGER"] %>


test:
  <<: *default
  username: <%= ENV["TEST_USERNAME"] %>
  host: <%= ENV["TEST_HOST"] %>
  password: <%= ENV["TEST_PASSWORD"] %>
  port: <%= ENV["TEST_PORT"] %>
  database: financial_manager_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL_FINANCIAL_MANAGER"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL_FINANCIAL_MANAGER"] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL_FINANCIAL_MANAGER"] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL_FINANCIAL_MANAGER"] %>
    migrations_paths: db/cable_migrate
