class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
  has_many :writing_books, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :financial_goals, dependent: :destroy
  has_many :incomes, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :weight_entries, dependent: :destroy
  has_one :health_profile, dependent: :destroy
  has_many :daily_calorie_entries, dependent: :destroy
  has_many :weekly_health_plans, dependent: :destroy
  has_many :weekly_health_goals, through: :weekly_health_plans
  has_many :health_journal_entries, dependent: :destroy
  has_many :health_weekly_reflections, dependent: :destroy
  has_many :weekly_health_reviews, dependent: :destroy
  has_many :weekly_wellbeings, dependent: :destroy
  has_many :health_wins, dependent: :destroy
  has_many :health_weight_goals, dependent: :destroy
  has_many :exercise_entries, dependent: :destroy
  has_many :strength_exercise_catalogs, dependent: :destroy
  has_many :muscle_groups, dependent: :destroy
  has_many :passkey_credentials, dependent: :destroy
end
